spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: AAAA0000
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQL8Dialect
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
  jwt:
    secret: G+KbPeShVmYq3t6v9y$B&E)H@McQfTjWnZr4u7x!z%C*F-JaNdRgUkXp2s5v8y/B
  mail:
    host: smtp.gmail.com
    port: 587
    username: sdsfs
    password:
    properties:i
      mail:
        smtp:
          auth: true
          starttls:
            enable: true